### ISSUE TITLE
Use open LLMs instead of openai

### ISSUE THREAD

**Issue by hardik1408** [c2siorg/b0bot#16]
**Is your feature request related to a problem? Please describe.**
It is expensive to use openai credentials in an open source project. Moreover, getting free credits is also not viable.

**Describe the solution you'd like**
I propose to use open LLMs like mistral,llama,gemma etc. We can use `ollama` to deploy these LLMs.
Would like to start working on the same.

**Comment by denxxs** [comment]
Hey,

I will try to solve this by using a fine-tuned, lightweight, open-source LLM. Will create a pull request once completed.

**Comment by hardik1408** [comment]
hey @denxxs 
I have already created a pull request #18 for the same. 
You can though suggest changes in the same . If required, we can work on something together.
