### ISSUE TITLE
Greeting from participant of GSoC

### ISSUE THREAD

**Issue by CoToYo** [c2siorg/b0bot#2]
Dear sir,

I am Tingyuan, a CS student in Boston University.
I just saw this project in the GSoC project board and I felt really interested in it . I think it would be a wonderful and meaningful project to work on. I know this project is still in its infancy, so maybe I could have some voluntary contribution in previous to not only help me have a better knowledge of this project, but also push the project forward.

Thank you and hope to hear from you soon.

**Comment by TsarPrince** [comment]
If there is any update, I would also love to work on this project collaboratively with @CoToYo :)

**Comment by YashasviChaurasia** [comment]
Interested.
